syntax on
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set listchars=trail:·,lead:·
set mouse=a
set list
set colorcolumn=80
highlight link Include NONE
highlight link cStorageClass NONE
highlight link cType NONE
highlight cString ctermfg=GREEN
highlight link cFloat NONE
highlight link cNumber NONE
highlight link cStatement NONE
